title: "Coding for Lawyers"
repo: "https://github.com/vzvenyach/codingforlawyers"

collections:
  chapters:
    output: true
    permalink: "/chapters/:path/"

defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"

markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
